services:  
  db:
    image: mysql:8.0
    container_name: ecommerce_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce_store
    ports:
      - '3307:3306'
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      # - ./mysql/data/:/var/lib/mysql

  webapp:
    build: .
    container_name: ecommerce_webapp
    env_file:
      - .env.docker
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app