services:
  db:
    image: mysql:8.0
    container_name: ecommerce_db
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ=Asia/Bangkok
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql